{% set name = "tini" %}
{% set version = "0.18.0" %}
{% set sha256 = "1097675352d6317b547e73f9dc7c6839fd0bb0d96dafc2e5c95506bb324049a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/krallin/tini/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - python
  host:

test:
  commands:
    - tini -h

about:
  home: https://github.com/krallin/tini
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tiny but valid `init` for containers

extra:
  recipe-maintainers:
    - jakirkham
