{% set name = "tini" %}
{% set version = "0.19.0" %}
{% set sha256 = "0fd35a7030052acd9f58948d1d900fe1e432ee37103c5561554408bdac6bbf0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/krallin/tini/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - python
    - make
  host:

test:
  commands:
    - tini -h

about:
  home: https://github.com/krallin/tini
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tiny but valid `init` for containers

extra:
  recipe-maintainers:
    - jakirkham
