appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qUBr6T5UE0+W1xbd7MKEHtOUbYSveyZSZHRtmqfxK9Kegg5TgkJvjJ7K/fPqx/u+xSUjpBtU9c0Lz8zzp+4kss3ls7DgIkByQKbRk7jHpXsFRo3qkg6BwJhTEYA6iog792i0tRQDBJL30vWP8vgMsm9w/rdd8LOQ87nTKB3QqEKBpa3UajM5O70OhJuWEzU7zDQZCEX8TxObnKguaeN+9LRWdtoyaoP8TohZ/dLZjv8atrmYbjQWjZOUKc3bDYhg6W4fTgbxo4tC/LSUgAPxnbAYdVyEeQVRumseRAeuvbNe9g5ld69vD5QBLQuLGk4Jtg8js2MgTn6npUOVboCgf9lL2NyLiibBakWXMOQjQZAP/nh6ZNAOtxjwHu4NHlGhhhYbz/bhTSyRwa1brMT2n1P89QMfSyEgBBDqOcNmNenWybdVlYSytLSkZfl6V2KSzu4oa6rDL7+LrKg8VZ/VjL7zI2iobBcR/60f44XAO2NosEiCdzY3pNmCpj37cwEFlf4DUfc2YIhgmRlswXQs7MlXoWyNT/sz81Fo+tPv7vF/Q/yfmgD443mYXd/4M0GrYRBOiEINoyFFwxHyL7i5jvC540YDVXDGfGhFYg2f7cKLQxNEJPR5nCettjOY8es0jd0sgeXvg3cMZbo33RgYchbSZSU7xuo3vhKKh3U7i8A=}
